Return-Path: <mihai.secasiu@gmail.com>
Delivered-To: mihai.secasiu@denixsolutions.com
X-Spam-Checker-Version: SpamAssassin 3.1.8 (2007-02-13) on
	obiwan.denixsolutions.com
X-Spam-Level: 
X-Spam-Status: No, score=-0.6 required=5.0 tests=AWL,BAYES_40,
	DK_POLICY_SIGNSOME,DK_SIGNED,HTML_MESSAGE,HTML_SHORT_LENGTH,SPF_PASS
	autolearn=no version=3.1.8
Received: (qmail 62336 invoked by uid 98); 3 May 2007 20:38:15 +0000
DomainKey-Status: good        
Received: from 64.233.184.234 by obiwan.denixsolutions.com (envelope-from <mihai.secasiu@gmail.com>, uid 0) with qmail-scanner-1.25 
 (clamdscan: 0.90/3069.  
 Clear:RC:0(64.233.184.234):. 
 Processed in 0.108523 secs); 03 May 2007 20:38:15 -0000
X-Qmail-Scanner-Mail-From: mihai.secasiu@gmail.com via obiwan.denixsolutions.com
X-Qmail-Scanner: 1.25 (Clear:RC:0(64.233.184.234):. Processed in 0.108523 secs)
Received: from unknown (HELO wr-out-0506.google.com) (64.233.184.234)
  by obiwan.denixsolutions.com with SMTP; 3 May 2007 20:38:15 +0000
Received: by wr-out-0506.google.com with SMTP id 60so664617wri
        for <mihai.secasiu@denixsolutions.com>; Thu, 03 May 2007 13:38:15 -0700 (PDT)
DKIM-Signature: a=rsa-sha1; c=relaxed/relaxed;
        d=gmail.com; s=beta;
        h=domainkey-signature:received:received:message-id:date:from:to:subject:mime-version:content-type;
        b=uEUXaa8ft7fvVxLhNrcG3SJaKsR5A0lF9gSXyg3S75edHRAX6DYTovtBRyEqkQaEtINo/6PqcvMJjiR5mw00ePbGajaxpGxXpqGhYXbVbAhLL+kGrdsj2kJauQR0NnatVAxFHfiWkfOhw+zgtP/FnQLb3yYuI+Cr8WuPmVC8t1Q=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=beta;
        h=received:message-id:date:from:to:subject:mime-version:content-type;
        b=XkgYJkxyl5r4Yi2+p247jY/bSXoL81fPcdJquq3lRyIEM5px3aMwFcf1ZDjVvTnaFRUgk3pSCWU0QtARhUDXmUMQUmyrIMvh5P1Nj0DSJ1IMQRCcJPoHVWTqXUQYoqugEdLK8WwqbNeKsVlWnMxWRK82r2BgOCoK3RLTE8/zz8g=
Received: by 10.78.149.15 with SMTP id w15mr1140223hud.1178224694426;
        Thu, 03 May 2007 13:38:14 -0700 (PDT)
Received: by 10.78.17.12 with HTTP; Thu, 3 May 2007 13:38:13 -0700 (PDT)
Message-ID: <f5ba5be60705031338n118c4dfcgc824e95174dc1d84@mail.gmail.com>
Date: Thu, 3 May 2007 23:38:13 +0300
From: "Mihai Secasiu" <mihai.secasiu@gmail.com>
To: "Mihai Secasiu" <mihai.secasiu@denixsolutions.com>
Subject: rttees
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_33559_28325216.1178224693622"

------=_Part_33559_28325216.1178224693622
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

dfdfs

------=_Part_33559_28325216.1178224693622
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

dfdfs

------=_Part_33559_28325216.1178224693622--

