Received: (qmail 30818 invoked for bounce); 1 May 2007 08:34:23 -0000
Date: 1 May 2007 08:34:23 -0000
From: MAILER-DAEMON@gw.home.denixtech.net
To: tugdgyuqingfaw@dgyuqing.com
Subject: failure notice

Hi. This is the qmail-send program at gw.home.denixtech.net.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<bacon@nixf.com>:
Sorry, no mailbox here by that name. (#5.1.1)

<ia@nixf.com>:
Sorry, no mailbox here by that name. (#5.1.1)

<pharmacy231@nixf.com>:
Sorry, no mailbox here by that name. (#5.1.1)

--- Below this line is a copy of the message.

Return-Path: <tugdgyuqingfaw@dgyuqing.com>
Received: (qmail 30808 invoked from network); 1 May 2007 08:34:22 -0000
Received: from ciq3.neoplus.adsl.tpnet.pl (83.31.40.3)
  by sport-fabricii.cluj.astral.ro with SMTP; 1 May 2007 08:34:22 -0000
Return-Path: <tugdgyuqingfaw@dgyuqing.com>
Received: from 61.152.90.228 (HELO m003.shilian.net)
     by nixf.com with esmtp (A80*/6B62. -?6-M6)
     id 5)TEF1-5V3MDS-,8
     for bacon@nixf.com; Tue, 1 May 2007 08:34:25 -0100
Date:	Tue, 1 May 2007 08:34:25 -0100
From:	"Sophia Ham" <tugdgyuqingfaw@dgyuqing.com>
X-Mailer: The Bat! (v3.5) UNREG / CD5BF9353B3B7091
X-Priority: 3 (Normal)
Message-ID: <019845118.73214987043241@thhebat.net>
To: bacon@nixf.com
Subject: Achieve picture perfect weight and enjoy life
MIME-Version: 1.0
Content-Type: multipart/alternative;
  boundary="----------CF8401096EC8B6E"
X-Spam: Not detected

------------CF8401096EC8B6E
Content-Type: text/plain; charset=iso-8859-2
Content-Transfer-Encoding: 7bit


Anatrim – The up-to-the-moment and most attracting lose flesh product is now readily available – As could be seen on ABC
Did you know excessive body kilograms kill a plenty of people every year? We know you hate the unattractive look of those people and the social prejudice against them. 

Moreover, you can’t withstand a siege of your ruinous eating habits. Does it sound familiar? Then we have something for you!

Introducing Anatrim, the new product for the elimination of your body’s extra weight. The greatest thing about Anatrim is it improves the quality of your life by making you feel no hungry and giving you better cheer. Here you may read what people write on this product:

"This is amazing! 

I stopped stuffing myself with food and watching TV constantly 

I became more interested in doing sport.

 Anatrim put me on the right track.

 I’m more fit now and there are lots of men around me!"

Amelia B., New York

"Passive weight burning was of little help to me. I could not restrain my ravenous hunger. 

Once I was told about Anatrim the media by and it brought a great influence on me.

 I had tried using it, and my wife said to me I had changed for the better since then, 3 months later. 

35 pounds off and I keep losing them! 

And you know, I’m an impetuous lover again."

Mike Brown, Las Vegas

Anatrim helps your mind to realize that you doesn’t have such a great need for that much food. It improves your mood, gives you additional energy, and attacks needless kilos. Great thanks to its powerful comprehensive formula!!
Elicit more! 

------------CF8401096EC8B6E
Content-Type: text/html; charset=iso-8859-2
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML><HEAD><TITLE>Make yourself more attractive to others</TITLE>
</HEAD>
<BODY>

<p>
<center>
<b>
<a href="http://www.shloudey.net/?g3676873737D33746674456E6B6872w7zaranz">Anatrim – The up-to-the-moment and most attracting lose flesh product is now readily available – As could be seen on ABC</a>
</b>
</center>
<b>
Did you know excessive body kilograms kill a plenty of people every year? We know you hate the unattractive look of those people and the social prejudice against them. 
<b>
Moreover, you can’t withstand a siege of your ruinous eating habits. Does it sound familiar? Then we have something for you!
</b>
</b>
<br>
<br>
<b>
Introducing Anatrim, the new product for the elimination of your body’s extra weight. The greatest thing about Anatrim is it improves the quality of your life by making you feel no hungry and giving you better cheer. Here you may read what people write on this product:
</b>
<br>
<br>
<b>
<i>
"This is amazing! 
<b>
<i>
I stopped stuffing myself with food and watching TV constantly 
<b>
<i>
I became more interested in doing sport.
</i>
</b>
</i>
</b>
<b>
<i>
 Anatrim put me on the right track.
</i>
</b>
 I’m more fit now and there are lots of men around me!"
</i>
</b>
<br>
<br>
<b>
<i>
Amelia B., New York
</i>
</b>
<br>
<br>
<b>
<i>
"Passive weight burning was of little help to me. I could not restrain my ravenous hunger. 
<b>
<i>
Once I was told about Anatrim the media by and it brought a great influence on me.
</i>
</b>
 I had tried using it, and my wife said to me I had changed for the better since then, 3 months later. 
<b>
<i>
35 pounds off and I keep losing them! 
</i>
</b>
And you know, I’m an impetuous lover again."
</i>
</b>
<br>
<br>
<b>
<i>
Mike Brown, Las Vegas
</i>
</b>
<br>
<br>
<b>
Anatrim helps your mind to realize that you doesn’t have such a great need for that much food. It improves your mood, gives you additional energy, and attacks needless kilos. Great thanks to its powerful comprehensive formula!!
</b>
<b>
<center>
<a href="http://www.shloudey.net/?g3676873737D33746674456E6B6872w7zaranz">Elicit more!</a>
</center>
</b>
</p> 

</BODY></HTML>
------------CF8401096EC8B6E--

